# -*- coding: utf-8 -*-
"""Code3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEwfVm8GjWnO5HpfBuf9ZF49N-6NjLi2
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

# --- PAGE CONFIG ---
st.set_page_config(page_title="Institutional Fee Architect", page_icon="⚖️", layout="wide")

# --- CUSTOM CSS ---
st.markdown("""
    <style>
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; border: 1px solid #eee; }
    .main { background-color: #f8f9fa; }
    .stButton>button { border-radius: 5px; background-color: #1e293b; color: white; }
    </style>
    """, unsafe_allow_html=True)

if 'years_count' not in st.session_state:
    st.session_state.years_count = 3

# --- SIDEBAR ---
with st.sidebar:
    st.title("⚖️ Deal Terms")
    with st.expander("💼 Capital & Base Fees", expanded=True):
        initial_value = st.number_input("Initial Investment", value=1000000.0)
        base_mgmt = st.number_input("Mgmt Fee (%)", value=2.0) / 100
        mgmt_basis = st.selectbox("Fee Basis", ["Opening Balance", "Closing Balance"])

    with st.expander("🎯 Performance Structure", expanded=True):
        base_perf = st.number_input("Perf Fee (%)", value=20.0) / 100
        perf_basis = st.selectbox("Logic", ["Independent", "Net of Management Fee"])
        hurdle_rate = st.number_input("Hurdle Rate (%)", value=8.0) / 100
        hurdle_type = st.radio("Style", ["Hard Hurdle", "Soft Hurdle"], horizontal=True)
        use_hwm = st.toggle("High-Water Mark (HWM)", value=True)

    with st.expander("🔬 Sensitivity"):
        step_size = st.slider("Step Size (%)", 0.1, 2.0, 0.5) / 100

st.title("Institutional Performance & Fee Architect")

# --- DYNAMIC GROWTH INPUTS ---
st.write("### 📅 Annual Growth Projections")
c1, c2, _ = st.columns([1, 1, 8])
with c1:
    if st.button("➕ Add Year"): st.session_state.years_count += 1
with c2:
    if st.button("➖ Remove Year") and st.session_state.years_count > 1: st.session_state.years_count -= 1

growth_rates = []
grid_cols = st.columns(5)
for i in range(st.session_state.years_count):
    with grid_cols[i % 5]:
        rate = st.number_input(f"Year {i+1} (%)", value=10.0, key=f"g_in_{i}")
        growth_rates.append(rate / 100)

# --- THE HERMETIC CALCULATION ENGINE ---
def run_full_simulation(g_list, m_rate, p_rate):
    sim_data = []
    c_opening = initial_value
    c_hwm = initial_value

    for idx, g in enumerate(g_list):
        gross_c = c_opening * (1 + g)
        m_fee = (c_opening if mgmt_basis == "Opening Balance" else gross_c) * m_rate

        h_amt = c_opening * hurdle_rate
        threshold = max(c_hwm, c_opening + h_amt) if use_hwm else (c_opening + h_amt)
        compare_val = (gross_c - m_fee) if perf_basis == "Net of Management Fee" else gross_c

        p_fee = 0.0
        if compare_val > threshold:
            if hurdle_type == "Hard Hurdle":
                p_fee = (compare_val - threshold) * p_rate
            else:
                p_base = c_hwm if use_hwm else c_opening
                p_fee = max(0, (compare_val - p_base) * p_rate)

        net_closing = gross_c - m_fee - p_fee

        sim_data.append({
            "Year": idx + 1,
            "Opening Bal": c_opening,
            "Growth (%)": g * 100, # STICKING TO THIS NAME
            "Mgmt Fee": m_fee,
            "Perf Fee": p_fee,
            "Net Closing": net_closing,
            "HWM": c_hwm if use_hwm else 0
        })

        if use_hwm: c_hwm = max(c_hwm, net_closing)
        c_opening = net_closing

    return pd.DataFrame(sim_data)

# --- EXECUTION ---
df_main = run_full_simulation(growth_rates, base_mgmt, base_perf)

# --- DASHBOARD METRICS ---
st.markdown("---")
f_net = df_main["Net Closing"].iloc[-1]
t_fees = df_main["Mgmt Fee"].sum() + df_main["Perf Fee"].sum()
cagr = ((f_net / initial_value)**(1/len(growth_rates)) - 1) * 100

m1, m2, m3, m4 = st.columns(4)
m1.metric("Final Net Value", f"${f_net:,.0f}")
m2.metric("Portfolio CAGR", f"{cagr:.2f}%")
m3.metric("Total Management Fees", f"${df_main['Mgmt Fee'].sum():,.0f}")
m4.metric("Total Performance Fees", f"${df_main['Perf Fee'].sum():,.0f}")

# --- VISUALS ---
v1, v2 = st.columns([7, 3])
with v1:
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df_main["Year"], y=df_main["Net Closing"], name="Net Value", line=dict(color='#66B2FF', width=3), fill='tozeroy'))
    if use_hwm:
        fig.add_trace(go.Scatter(x=df_main["Year"], y=df_main["HWM"], name="Watermark", line=dict(color='#ef4444', dash='dot')))
    fig.update_layout(title="Capital Appreciation vs. High-Water Mark", template="simple_white", margin=dict(l=0, r=0, t=30, b=0))
    st.plotly_chart(fig, use_container_width=True)
with v2:
    fig_pie = px.pie(names=['Investor Profit', 'Total Fees'],
                     values=[max(0, f_net - initial_value), t_fees],
                     color_discrete_sequence=['#003057', '#66B2FF'], hole=0.6)
    fig_pie.update_layout(showlegend=False, margin=dict(l=20, r=20, t=30, b=20))
    st.plotly_chart(fig_pie, use_container_width=True)

# --- ANNUAL DETAIL TABLE ---
st.markdown("---")
st.write("### 📄 Annual Performance Breakdown")

df_detail = df_main.copy()

# Compute total expense
df_detail["Total Expense"] = df_detail["Mgmt Fee"] + df_detail["Perf Fee"]

# Compute annual net return percentage
df_detail["Annual Return (%)"] = (
    (df_detail["Net Closing"] - df_detail["Opening Bal"]) /
    df_detail["Opening Bal"].replace(0, np.nan)
) * 100

# Prepare clean display
df_display = df_detail[[
    "Year",
    "Opening Bal",
    "Growth (%)",
    "Mgmt Fee",
    "Perf Fee",
    "Total Expense",
    "HWM",
    "Net Closing",
    "Annual Return (%)"
]]

st.dataframe(
    df_display.style.format({
        "Opening Bal": "{:,.2f}",
        "Mgmt Fee": "{:,.2f}",
        "Perf Fee": "{:,.2f}",
        "Total Expense": "{:,.2f}",
        "HWM": "{:,.2f}",
        "Net Closing": "{:,.2f}",
        "Growth (%)": "{:.2f}",
        "Annual Return (%)": "{:.2f}"
    }),
    use_container_width=True
)
